# Generated by Django 5.0.1 on 2024-02-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0001_initial'),
        ('doctors', '0004_remove_clinic_clinic_images_clinic_clinic_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.RemoveField(
            model_name='educations',
            name='present',
        ),
        migrations.AddField(
            model_name='experiences',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
