# Generated by Django 5.0.1 on 2024-02-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0002_schedules_total_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='slot_duration',
            field=models.IntegerField(default=10),
        ),
    ]
