# Generated by Django 5.0.1 on 2024-02-17 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0002_delete_images_remove_educations_present_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educations',
            old_name='Institute',
            new_name='institute',
        ),
    ]
