# Generated by Django 5.0.1 on 2024-02-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0003_schedules_slot_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
