# Generated by Django 5.0.1 on 2024-02-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0003_rename_institute_educations_institute'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_image', models.ImageField(upload_to='clinic_images')),
            ],
        ),
    ]
