# Generated by Django 5.0.1 on 2024-02-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='picture',
            field=models.ImageField(null=True, upload_to='pictures/'),
        ),
    ]
