# Generated by Django 5.0.1 on 2024-02-27 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0003_reviews'),
        ('doctors', '0006_alter_slots_options_remove_slots_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('booked_time', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('updated_at', models.DateField(auto_now=True)),
                ('appointment_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.slots')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctors')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.patients')),
            ],
            options={
                'verbose_name_plural': 'APPOINTMENTS',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='BookingPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('status', models.CharField(default='paid', max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.appointments')),
            ],
        ),
    ]
