# Generated by Django 5.0.1 on 2024-02-19 14:49

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contexts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality_name', models.CharField(max_length=200)),
                ('speciality_image', models.ImageField(upload_to='specialities/')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'SPECIALITIES',
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('gender', models.CharField(default='Male')),
                ('consultation_fee', models.IntegerField(default=500)),
                ('services', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('about', models.TextField()),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('clinic_name', models.CharField(blank=True, max_length=200, null=True)),
                ('clinic_address', models.CharField(blank=True, max_length=500, null=True)),
                ('slot_duration', models.CharField(default='10 mins', max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('awards', models.ManyToManyField(blank=True, to='contexts.awards')),
                ('clinic_images', models.ManyToManyField(blank=True, to='contexts.clinicimages')),
                ('education', models.ManyToManyField(blank=True, to='contexts.educations')),
                ('experience', models.ManyToManyField(blank=True, to='contexts.experiences')),
                ('schedules', models.ManyToManyField(blank=True, to='contexts.schedules')),
                ('speciality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.speciality')),
            ],
            options={
                'verbose_name_plural': 'DOCTORS',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctors')),
            ],
            options={
                'verbose_name_plural': 'SLOTS',
                'ordering': ('-id',),
            },
        ),
    ]
