# Generated by Django 5.0.1 on 2024-02-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
