# Generated by Django 5.0.1 on 2024-02-16 04:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_rename_name_clinic_clinic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='clinic_images',
        ),
        migrations.AddField(
            model_name='clinic',
            name='clinic_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='images/'), blank=True, null=True, size=None),
        ),
    ]
