# Generated by Django 5.0.1 on 2024-02-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctors_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='slot_duration',
            field=models.IntegerField(default=10),
        ),
    ]
