# Generated by Django 5.0.1 on 2024-02-25 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_doctors_slot_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slots',
            options={'ordering': ('id',), 'verbose_name_plural': 'SLOTS'},
        ),
        migrations.RemoveField(
            model_name='slots',
            name='doctor',
        ),
        migrations.AlterField(
            model_name='slots',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SlotInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctors')),
            ],
            options={
                'unique_together': {('doctor', 'date')},
            },
        ),
        migrations.AddField(
            model_name='slots',
            name='slot_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.slotinstance'),
        ),
    ]
