# Generated by Django 5.0.1 on 2024-02-17 15:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0004_clinicimages'),
        ('doctors', '0006_alter_doctors_clinic_images_alter_doctors_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='clinic_images',
        ),
        migrations.AlterField(
            model_name='doctors',
            name='services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='doctors',
            name='clinic_images',
            field=models.ManyToManyField(blank=True, to='contexts.clinicimages'),
        ),
    ]
